(provide 'tq)

(defconst tq-c-style
  '((c-tab-always-indent . t)
    (c-basic-offset . 8)
    (c-comment-only-line-offset . 0)
    (c-echo-syntactic-information-p . t)
    (c-hanging-braces-alist . ((substatement-open after)
			       (inline-open after)
			       (class-open after)
			       ;; (class-close after)
			       (defun-open after)
			       ;; (defun-close after)
			       (brace-entry-open after)
			       (statement after)
			       (case-label after)
			       (else-case)
			       ;; (block-close before)
			       (access-label after)
			       (do-while-closure after)
			       (catch-clause after)
			       (member-init-intro after)
			       (brace-list-open after)))
    (c-hanging-colons-alist . ((member-init-intro before)
			       (inher-intro)
			       (case-label after)
			       (access-label after)))
    (c-cleanup-list . nil)
    (c-offsets-alist . ((substatement-open . 0)
			(label . 0)
			(case-label . 0)
			(block-open . 0))))
  "tq c style")

(c-add-style "tq-c-style" tq-c-style)
